
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 30 15:43:20 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int LPAREN = 41;
  public static final int SEMI = 38;
  public static final int CONTINUE = 15;
  public static final int MINUS = 19;
  public static final int RPAREN = 42;
  public static final int LT = 31;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 36;
  public static final int DIV = 21;
  public static final int GEQ = 30;
  public static final int PLUS = 18;
  public static final int IF = 7;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 35;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int BITOR = 34;
  public static final int MUL = 20;
  public static final int LAMBDAOP = 28;
  public static final int NUMBER = 47;
  public static final int MOD = 22;
  public static final int NEQ = 24;
  public static final int BREAK = 3;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int EQ = 23;
  public static final int COLON = 44;
  public static final int FOREACH = 16;
  public static final int LANGLE = 43;
  public static final int LBRACE = 26;
  public static final int ELSE = 5;
  public static final int ENUM = 46;
  public static final int READ = 11;
  public static final int CHARCONST = 48;
  public static final int WHILE = 8;
  public static final int RANGLE = 25;
  public static final int RBRACE = 27;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int BITAND = 33;
  public static final int DEC = 37;
  public static final int GT = 29;
  public static final int DO = 45;
  public static final int PRINT = 10;
}

